sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

#before_install:

install:
  - ./tutorial.sh -r

script:
  - ./tutorial.sh -t

after_script:
  - ./tutorial.sh -r

#notifications:
  # notify ansible galaxy of test results
 # webhooks: http://galaxy-qa.ansible.com/api/v1/notifications/
